### ISSUE TITLE
Media queries not working as expected

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/game-project#209]
I've created my gameboard and used media queries to make it mobile friendly.

It's working perfectly on mobile for both portrait and landscape when I check using Chrome's dev tools.

For some reason, the game board is not showing up as max-width of 550px like I want it to on desktop though.

I've read MDN's documentation, a few blog posts, Stack Overflow answers, and the past Issues. Can't seem to pinpoint what I'm doing wrong though.

Any change I make that makes it look the way I want on desktop, seems to make it change on mobile landscape also and I don't get why.

[HTML](https://github.com/gabescarbrough/tic-tac-toe/blob/html/index.html)
[SCSS](https://github.com/gabescarbrough/tic-tac-toe/blob/html/assets/styles/gameboard.scss)

**Comment by laurenfazah** [comment]
Could be your orientation queries causing conflicts. On desktop, with the viewport at the size you'd expect a max-width of 550px, what styles do you see applied to `.board` in Chrome's dev tools console?

**Comment by gabescarbrough** [comment]
.board is getting the mobile landscape style in Chrome's dev tools

``` scss
@media only screen and (min-width: 600px) and (orientation: landscape)
.board {
    max-width: 400px;
}
```

Tried to change the media query to

``` scss
@media only screen and (min-width: 600px) and (max-width: 700px) and (orientation: landscape)
.board {
    max-width: 400px;
}
```

to make it not apply on desktop where the resolution is higher than that, but that makes it not work  correctly on mobile landscape anymore. I've always found min-width and max-width confusing for media queries so I think it could be the numbers I'm using?
