### ISSUE TITLE
Bootstrap nullify styles: Reserved Classes

### ISSUE THREAD

**Issue by sjf125** [ga-wdi-boston/game-project#57]
I have rounded squares with a light green color that has a hover effect, but when I enable bootstrap, they all become light yellow un-rounded squares with no hover effect.  For the time being I have disabled bootstrap styling by commenting out the @import so I have the styling I want.  I have gone over my scss files and my html to see if removing classes or moving things around would help, to no avail.  Below is the code I have:

index.scss:

``` scss
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
// @import '~bootstrap-sass/assets/stylesheets/bootstrap';
@import 'breakpoints';
@import 'colors';
@import 'typography';
@import 'board';
@import 'cells';
@import 'scoreboard';
```

cells.scss:

``` scss
.cell {
  background-color: $cell;
  border-radius: 10px;
  float: left;
  margin: 1%;
  padding-bottom: 31.33%; // = width for a 1:1 aspect ratio //
  position: relative;
  width: 31.33%;
}

.cell:hover {
  background-color: $cell-hover;
  box-shadow: 0 0 1em $cell-highlight;
}

.mark {
  height: 100%; // = 100% - 2*5% padding //
  position: absolute;
  text-align: center;
  width: 100%; // = 100% - 2*5% padding //
}
```

colors.scss:

``` scss
$text-default: #383838;
$cell: #D8F39A;
$cell-hover: lighten($cell, 70%);
$cell-highlight: #F6FCDD;
$border: #000;

/// Slightly lighten a color
/// @param {Color} $color - color to tint
/// @param {Number} $percentage - percentage of `$color` in returned color
@function tint($color, $percentage) {
  @return mix(white, $color, $percentage);
}

/// Slightly darken a color
/// @param {Color} $color - color to shade
/// @param {Number} $percentage - percentage of `$color` in returned color
@function shade($color, $percentage) {
  @return mix(black, $color, $percentage);
}
```

index.html:

``` html
<!DOCTYPE html>
<html>
    <head>
      <title>Tic Tac Toe!</title>

      <script src="vendor.bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
    </head>
    <body class="container-fluid">
      <h1>Tic Tac Toe!</h1>

          <div class="board">
            <div class="cell">
              <div class="mark"><h2 id="a1"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="a2"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="a3"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="b1"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="b2"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="b3"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="c1"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="c2"></h2></div>
            </div>
            <div class="cell">
              <div class="mark"><h2 id="c3"></h2></div>
            </div>
          </div>

          <footer>
            <div class="player x">
              <h2 class="x">X</h2>
              <h1 class="score x">1</h1>
            </div>
            <div class="player o">
              <h2 class="o">O</h2>
              <h1 class="score o">1</h1>
            </div>
          </footer>
    </body>
</html>
```
