### ISSUE TITLE
game board show/hide bug (jquery/css)

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/game-project#652]
My board is set as ```visibility: hidden``` in CSS initially, so i set  ```$('#board').css('visibility', 'visible')``` to make it appear when createGameSuccess function is called. However, my board will not appear unless I have ```  $('#board').show()```, which should be unnecessary. Cannot find anywhere in code that assigns #board to .hide(). I would appreciate any feedback. Thank you.

CSS
```css
#board, #change-password, #sign-out, #create-game, #get-games, #get-game {
  visibility: hidden;
}

.board {
  background-color: blue;
  height: 500px;
  margin: auto;
  outline: 1px solid red;
  width: 500px;
}
```

Javascript
```js
const createGameSuccess = (response) => {
  console.log('game created successfully!')
  console.log('Game object is: ', response)
  $('.status-message').text('Game time!')
  $('#board').show()
  $('#board').css('visibility', 'visible')
  store.game = response.game
  console.log('game is stored as: ', store.game)
}
```

HTML
```html
<div id="board" class="board">
    <button id="box0" class="box row-one column-one one" name="game[cell]"></button>
    <button id="box1" class="box row-one column-two two"></button>
    <button id="box2" class="box row-one column-three three"></button>
    <button id="box3" class="box row-two column-one four"></button>
    <button id="box4" class="box row-two column-two five"></button>
    <button id="box5" class="box row-two column-three six"></button>
    <button id="box6" class="box row-three column-one seven"></button>
    <button id="box7" class="box row-three column-two eight"></button>
    <button id="box8" class="box row-three column-three nine"></button>
  </div>
```

**Comment by tvcrawley** [comment]
In dev tools, when `visibility` is turned to `visible`, what styling does your `#board` have?

**Comment by nriser** [comment]
Thank you for your response. It's set to display: none, but nowhere in my index.scss page do I have that. After I click on "create new games" that fires the createGameSuccess button, it changes to visibility: visible

my entire css code. I don't have a separate css file. 
```css
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';

#board, #change-password, #sign-out, #create-game, #get-games, #get-game {
  visibility: hidden;
}

.board {
  background-color: blue;
  height: 500px;
  margin: auto;
  outline: 1px solid red;
  width: 500px;
}

.message {
  // border: 3px solid blue;
  height: 400px;
  width: 100%;
}

.box {
  color: black;
  float: left;
  font-family: sans-serif;
  font-size: 100px;
  height: 33.3%;
  line-height: 150px;
  margin: 0;
  outline: 1px solid blue;
  padding: 0;
  text-align: center;
  width: 33.3%;
}

.box:hover {
  background-color: gray;
}

.message {
  margin-top: 20px;
  text-align: center;
}

.show-games-container, .show-game-container {
  // border: 2px solid green;
  background-color: black;
  color: white;
  width: 100%;
  height: auto;
}
```
