### ISSUE TITLE
Making an SCSS gameboard

### ISSUE THREAD

**Issue by mak1323** [ga-wdi-boston/game-project#775]
So I tried to do a gameboard through scss and html, using  the following code:
```html  
<div class="container">
    <div class="game-box">
      <div class="row">
        <div class="col-xs-4 box" id="gameBoxTopLeft">
          <div class="game-box-top-left">
            <p>gameBoxTopLeft [0,0]</p>
          </div>
        </div>
        <div class="col-xs-4 box" id="gameBoxTopMiddle">
          <div class="game-box-top-middle">
            <p>gameBoxTopMiddle [0,1]</p>
          </div>
        </div>
        <div class="col-xs-4 box" id="gameBoxTopRight">
          <div class="game-box-top-right">
            <p>gameBoxTopRight [0,2]</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 box" id="gameBoxMiddleLeft">
          <div class="game-box-middle-left">
            <p>gameBoxMiddleLeft [1,0]</p>
          </div>
        </div>
        <div class="col-xs-4 box" id="gameBoxMiddleMiddle">
          <div class="game-box-middle-middle">
            <p>gameBoxMiddleMiddle [1,1]</p>
          </div>
        </div>
        <div class="col-xs-4 box" id="gameBoxMiddleRight">
          <div class="game-box-middle-right">
            <p>gameBoxMiddleRight [1,2]</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 box" id="gameBoxBottomLeft">
          <div class="game-box-bottom-left">
            <p>gameBoxBottomLeft[2,0]</p>
          </div>
        </div>
        <div class="col-xs-4 box" id="gameBoxBottomMiddle">
          <div class="game-box-bottom-middle">
            <p>gameBoxBottomMiddle [2,1]</p>
          </div>
        </div>
        <div class="col-xs-4 box" id="gameBoxBottomRight">
          <div class="game-box-bottom-right">
            <p>gameBoxBottomRight [2,2] </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- the sign in form -->
  <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabelSignIn">Signing In</h4>
        </div>
        <div class="modal-body>">
          <form class="form-inline">
            <div class="form-group">
              <label class="sr-only" for="inputEmail">Email address</label>
              <input type="email" class="form-control" id="inputEmail" placeholder="Email">
            </div>
            <div class="form-group">
              <label class="sr-only" for="inputPassword">Password</label>
              <input type="password" class="form-control" id="inputPassword" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Sign In</button>
          </form>
        </div>
      </div>
    </div>
  </div>
```

```scss
.game-box-top-left {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 0 10px 10px 0;

}

.game-box-top-middle {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 0 10px 10px 10 px;
}

.game-box-top-right {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 0 0 10px 10px;
}

.game-box-middle-left {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 10px 10px 10px 0;
}

.game-box-middle-middle {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 10px;
}

.game-box-middle-right {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 10px 0 10px 10px;
}

.game-box-bottom-left {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 10px 10px 0 0;
}

.game-box-bottom-middle {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 10px 10px 0 10px;
}

.game-box-bottom-right {
  align-content: center;
  background-color: $pure-white;
  max-height: 200px;
  max-width: 200px;
  min-height: 30px;
  min-width: 30px;
  padding: 10px 0 0 10px;
}
```
I'm trying to do it this way as opposed to pulling an image and trying to layer anchors on top. I'm about to scour the other issues to see where I am, but first I want to try to margins instead of padding.

**Comment by mak1323** [comment]
....I'm not sure what just happened to all my html on my post...

**Comment by Jcornmanhomonoff** [comment]
@mak1323 can you fix it so that it separates the html and css please?

**Comment by BenGitsCode** [comment]
Reference [this](https://help.github.com/articles/creating-and-highlighting-code-blocks/) if you're not familiar with the syntax

**Comment by mak1323** [comment]
Updated
 I'm wondering if it will be better to just import a board instead of trying to build one. 

The method behind this was to have each column piece be white on a black background, then have the board lines come through underneath behind the padding/margin.

The Margin side worked better, but not worth it enough for me to satisfied with it as a board.

**Comment by mak1323** [comment]
Solution: Error in KISS protocols...I did not keep it simple.
Problem resolved by cleaning up code, eliminating redundant SCSS, and instead putting my gameboard into a box grid.

New scss looks like this:

```scss
@import 'colors';

.game-box {
  background-color: $pure-black;
}

.box {
  background-color: $pure-white;
  border: 2px solid $pure-black;
}
```

Keeping it simple.
