### ISSUE TITLE
bootstrap having issues connecting to html

### ISSUE THREAD

**Issue by rtuttle611** [ga-wdi-boston/game-project#782]
my grid layout is not showing up due to bootstrap not connecting attaching part of my code.  

html...

```html

<div class='container gamebox'>
    <div class='row row-centered'>
      <div class='col-xs-4 game-cell col-centered'>
        <div class='cell-content' data-mark="''">
          <h1>Spot 1</h1>
        </div>
      </div>
      <div class="col-xs-4 game-cell col-centered box">
        <div class="cell-content" data-mark="''">
        <h1>Spot 1</h1>
      </div>
      </div>
      <div class="col-xs-4 game-cell col-centered">
        <div class="cell-content" data-mark="''">
        <h1>Spot 1</h1></div>
      </div>
```

```css
$cell-border-radius: 5px;
$cell-width: 18%;

.mark-x {
  background-color: red;
}

.mark-o {
  background-color: blue;
}

.col-xs-4 {
  border: solid 5px $black;
  border-radius: $cell-border-radius;
  // box-sizing: border-box;
  position: relative;
  width: $cell-width;
}
```

**Comment by Jcornmanhomonoff** [comment]
Are you getting an error?

**Comment by rtuttle611** [comment]
Im not receiving any errors with html. on css i have one obscure one "force-pseudo-nesting" with this part of css

```.col-xs-4::before {
  content: '';
  display: block;
  padding-top: 100%;
}```

**Comment by rtuttle611** [comment]
```css 
.col-xs-4::before {
  content: '';
  display: block;
  padding-top: 100%;
}
```

**Comment by Jcornmanhomonoff** [comment]
What are you attempting to do with this:

```css
.col-xs-4::before {
 content: '';
 display: block;
 padding-top: 100%;
}
```
